/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type TranscriptChunk = {
  _type: "transcriptChunk";
  startSeconds: number;
  text: string;
};

export type Chapter = {
  _type: "chapter";
  startSeconds: number;
  label: string;
};

export type Resource = {
  _type: "resource";
  type: "article" | "documentation" | "code" | "download" | "video" | "other";
  title: string;
  description?: string;
  url: string;
};

export type LearningOutcome = {
  _type: "learningOutcome";
  icon?: string;
  title: string;
  description?: string;
};

export type LessonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "lesson";
};

export type Module = {
  _type: "module";
  title: string;
  summary?: string;
  lessons?: Array<
    {
      _key: string;
    } & LessonReference
  >;
};

export type AssessmentGenerationRecord = {
  _id: string;
  _type: "assessmentGenerationRecord";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  kind?: "section" | "lesson_transfer";
  lesson?: LessonReference;
  spanIndex?: number;
  outcome?: "drafted" | "no_candidates" | "all_rejected";
  draftIds?: Array<string>;
  rejectionReasons?: Array<string>;
  modelSkipReason?: string;
  spanKey?: string;
  promptVersion?: string;
  model?: string;
  configVersion?: string;
  processedAt?: string;
};

export type Assessment = {
  _id: string;
  _type: "assessment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  reviewStatus: "needs_review" | "approved" | "rejected" | "archived";
  sourceStatus: "current" | "stale";
  lesson: LessonReference;
  objective: string;
  type: "recall" | "apply" | "transfer";
  responseFormat: "single_choice";
  question: string;
  options: Array<{
    text: string;
    _type: "assessmentOption";
    _key: string;
  }>;
  answerKey: {
    correctOptionId: string;
    correctReason: string;
    distractorReasons: Array<{
      optionId: string;
      reason: string;
      _type: "distractorReason";
      _key: string;
    }>;
  };
  hints: {
    direction: string;
    keyConcept: string;
    solution: string;
  };
  review?: {
    correct?: boolean;
    unambiguous?: boolean;
    distractorsPlausible?: boolean;
    sourceSupported?: boolean;
    difficultyAppropriate?: boolean;
    hintsProgressive?: boolean;
    note?: string;
  };
  sourceExcerpt?: string;
  sourceChunkRefs: Array<{
    chunkId?: string;
    chunkRevision?: string;
    startSeconds?: number;
    endSeconds?: number;
    _type: "sourceChunkRef";
    _key: string;
  }>;
  familyId: string;
  version: number;
  generation?: {
    spanKey?: string;
    inputHash?: string;
    spanIndex?: number;
    ordinal?: number;
    model?: string;
    promptVersion?: string;
    configVersion?: string;
    generatedAt?: string;
  };
};

export type Progress = {
  _id: string;
  _type: "progress";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  userId: string;
  lesson: LessonReference;
  completed?: boolean;
  completedAt?: string;
  resumeSeconds?: number;
  updatedAt?: string;
};

export type Video = {
  _id: string;
  _type: "video";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  videoId: string;
  provider: "youtube" | "vimeo" | "bunny";
  providerVideoId?: string;
  sourceUrl: string;
  title?: string;
  durationSeconds?: number;
  chapters?: Array<
    {
      _key: string;
    } & Chapter
  >;
  transcriptChunks?: Array<
    {
      _key: string;
    } & TranscriptChunk
  >;
  ingestedAt?: string;
};

export type Lesson = {
  _id: string;
  _type: "lesson";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  videoUrl?: string;
  poster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  durationSeconds?: number;
  notes?: BlockContent;
  keyPoints?: Array<string>;
  proTip?: string;
  resources?: Array<
    {
      _key: string;
    } & Resource
  >;
  freePreview?: boolean;
  studentCountDisplay?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type InstructorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "instructor";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Course = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  summary?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  level: "beginner" | "intermediate" | "advanced";
  instructor?: InstructorReference;
  category?: CategoryReference;
  learningOutcomes?: Array<
    {
      _key: string;
    } & LearningOutcome
  >;
  modules?: Array<
    {
      _key: string;
    } & Module
  >;
  priceDisplay?: string;
  popular?: boolean;
  studentCountDisplay?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
};

export type Instructor = {
  _id: string;
  _type: "instructor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  expertise?: Array<string>;
  bio?: string;
};

export type SanityAgentContext = {
  _id: string;
  _type: "sanity.agentContext";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  version?: string;
  name?: string;
  slug: Slug;
  groqFilter?: string;
  instructions?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | BlockContent
  | TranscriptChunk
  | Chapter
  | Resource
  | LearningOutcome
  | LessonReference
  | Module
  | AssessmentGenerationRecord
  | Assessment
  | Progress
  | Video
  | Lesson
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | InstructorReference
  | CategoryReference
  | Course
  | Category
  | Instructor
  | SanityAgentContext
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../sanity/queries/assessments.ts
// Variable: LESSON_PRACTICE_ITEMS_QUERY
// Query: *[    _type == "assessment" &&    lesson._ref == $lessonId &&    reviewStatus == "approved" &&    sourceStatus == "current" &&    !(_id in path("drafts.**")) &&    !(_id in path("versions.**")) &&    count(*[      _type == "assessment" &&      familyId == ^.familyId &&      version > ^.version &&      reviewStatus == "approved" &&      sourceStatus == "current" &&      !(_id in path("drafts.**")) &&      !(_id in path("versions.**"))    ]) == 0  ] | order(familyId asc, version desc)[0...50] {    _id,    _rev,    familyId,    version,    "lessonId": lesson._ref,    type,    responseFormat,    question,    "options": options[] { "id": _key, text }  }
export type LESSON_PRACTICE_ITEMS_QUERY_RESULT = Array<{
  _id: string;
  _rev: string;
  familyId: string;
  version: number;
  lessonId: string;
  type: "apply" | "recall" | "transfer";
  responseFormat: "single_choice";
  question: string;
  options: Array<{
    id: string;
    text: string;
  }>;
}>;

// Source: ../sanity/queries/categories.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category" && defined(slug.current)] | order(title asc) {      _id,  title,  "slug": slug.current,    description,    "courseCount": count(*[_type == "course" && category._ref == ^._id])  }
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  description: string | null;
  courseCount: number;
}>;

// Source: ../sanity/queries/categories.ts
// Variable: CATEGORY_BY_SLUG_QUERY
// Query: *[_type == "category" && slug.current == $slug][0] {      _id,  title,  "slug": slug.current,    description,    "courses": *[_type == "course" && category._ref == ^._id && defined(slug.current)]      | order(popular desc, title asc) {   _id,  title,  "slug": slug.current,  summary,  level,  priceDisplay,  popular,  studentCountDisplay,  coverImage {   _type,  alt,  hotspot,  crop,  asset->{    _id,    url,    metadata { lqip, dimensions { width, height, aspectRatio } }  } },  instructor->{   _id,  name,  "slug": slug.current,  expertise,  photo {   _type,  alt,  hotspot,  crop,  asset->{    _id,    url,    metadata { lqip, dimensions { width, height, aspectRatio } }  } } },  category->{   _id,  title,  "slug": slug.current },  "moduleCount": count(modules),  "lessonCount": count(modules[].lessons[]),  "durationSeconds": math::sum(modules[].lessons[]->durationSeconds) }  }
export type CATEGORY_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  description: string | null;
  courses: Array<{
    _id: string;
    title: string;
    slug: string;
    summary: string | null;
    level: "advanced" | "beginner" | "intermediate";
    priceDisplay: string | null;
    popular: boolean | null;
    studentCountDisplay: string | null;
    coverImage: {
      _type: "image";
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
            aspectRatio: number;
          } | null;
        } | null;
      } | null;
    } | null;
    instructor: {
      _id: string;
      name: string;
      slug: string;
      expertise: Array<string> | null;
      photo: {
        _type: "image";
        alt: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number;
              height: number;
              aspectRatio: number;
            } | null;
          } | null;
        } | null;
      } | null;
    } | null;
    category: {
      _id: string;
      title: string;
      slug: string;
    } | null;
    moduleCount: number | null;
    lessonCount: number | null;
    durationSeconds: number | null;
  }>;
} | null;

// Source: ../sanity/queries/courses.ts
// Variable: COURSES_QUERY
// Query: *[_type == "course" && defined(slug.current)]    | order(popular desc, title asc) {      _id,  title,  "slug": slug.current,  summary,  level,  priceDisplay,  popular,  studentCountDisplay,  coverImage {   _type,  alt,  hotspot,  crop,  asset->{    _id,    url,    metadata { lqip, dimensions { width, height, aspectRatio } }  } },  instructor->{   _id,  name,  "slug": slug.current,  expertise,  photo {   _type,  alt,  hotspot,  crop,  asset->{    _id,    url,    metadata { lqip, dimensions { width, height, aspectRatio } }  } } },  category->{   _id,  title,  "slug": slug.current },  "moduleCount": count(modules),  "lessonCount": count(modules[].lessons[]),  "durationSeconds": math::sum(modules[].lessons[]->durationSeconds)  }
export type COURSES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  summary: string | null;
  level: "advanced" | "beginner" | "intermediate";
  priceDisplay: string | null;
  popular: boolean | null;
  studentCountDisplay: string | null;
  coverImage: {
    _type: "image";
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
          aspectRatio: number;
        } | null;
      } | null;
    } | null;
  } | null;
  instructor: {
    _id: string;
    name: string;
    slug: string;
    expertise: Array<string> | null;
    photo: {
      _type: "image";
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
            aspectRatio: number;
          } | null;
        } | null;
      } | null;
    } | null;
  } | null;
  category: {
    _id: string;
    title: string;
    slug: string;
  } | null;
  moduleCount: number | null;
  lessonCount: number | null;
  durationSeconds: number | null;
}>;

// Source: ../sanity/queries/courses.ts
// Variable: COURSE_SLUGS_QUERY
// Query: *[_type == "course" && defined(slug.current)].slug.current
export type COURSE_SLUGS_QUERY_RESULT = Array<string>;

// Source: ../sanity/queries/courses.ts
// Variable: COURSE_BY_SLUG_QUERY
// Query: *[_type == "course" && slug.current == $slug][0] {      _id,  title,  "slug": slug.current,  summary,  level,  priceDisplay,  popular,  studentCountDisplay,  coverImage {   _type,  alt,  hotspot,  crop,  asset->{    _id,    url,    metadata { lqip, dimensions { width, height, aspectRatio } }  } },  instructor->{   _id,  name,  "slug": slug.current,  expertise,  photo {   _type,  alt,  hotspot,  crop,  asset->{    _id,    url,    metadata { lqip, dimensions { width, height, aspectRatio } }  } } },  category->{   _id,  title,  "slug": slug.current },  "moduleCount": count(modules),  "lessonCount": count(modules[].lessons[]),  "durationSeconds": math::sum(modules[].lessons[]->durationSeconds),    instructor->{   _id,  name,  "slug": slug.current,  expertise,  photo {   _type,  alt,  hotspot,  crop,  asset->{    _id,    url,    metadata { lqip, dimensions { width, height, aspectRatio } }  } }, bio },    learningOutcomes[] { _key, icon, title, description },    modules[] {      _key,      title,      summary,      lessons[]->{   _id,  title,  "slug": slug.current,  durationSeconds,  freePreview,  poster {   _type,  alt,  hotspot,  crop,  asset->{    _id,    url,    metadata { lqip, dimensions { width, height, aspectRatio } }  } } }    }  }
export type COURSE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  summary: string | null;
  level: "advanced" | "beginner" | "intermediate";
  priceDisplay: string | null;
  popular: boolean | null;
  studentCountDisplay: string | null;
  coverImage: {
    _type: "image";
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
          aspectRatio: number;
        } | null;
      } | null;
    } | null;
  } | null;
  instructor: {
    _id: string;
    name: string;
    slug: string;
    expertise: Array<string> | null;
    photo: {
      _type: "image";
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
            aspectRatio: number;
          } | null;
        } | null;
      } | null;
    } | null;
    bio: string | null;
  } | null;
  category: {
    _id: string;
    title: string;
    slug: string;
  } | null;
  moduleCount: number | null;
  lessonCount: number | null;
  durationSeconds: number | null;
  learningOutcomes: Array<{
    _key: string;
    icon: string | null;
    title: string;
    description: string | null;
  }> | null;
  modules: Array<{
    _key: string;
    title: string;
    summary: string | null;
    lessons: Array<{
      _id: string;
      title: string;
      slug: string;
      durationSeconds: number | null;
      freePreview: boolean | null;
      poster: {
        _type: "image";
        alt: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number;
              height: number;
              aspectRatio: number;
            } | null;
          } | null;
        } | null;
      } | null;
    }> | null;
  }> | null;
} | null;

// Source: ../sanity/queries/instructors.ts
// Variable: INSTRUCTORS_QUERY
// Query: *[_type == "instructor" && defined(slug.current)] | order(name asc) {      _id,  name,  "slug": slug.current,  expertise,  photo {   _type,  alt,  hotspot,  crop,  asset->{    _id,    url,    metadata { lqip, dimensions { width, height, aspectRatio } }  } },    "courseCount": count(*[_type == "course" && instructor._ref == ^._id])  }
export type INSTRUCTORS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  expertise: Array<string> | null;
  photo: {
    _type: "image";
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
          aspectRatio: number;
        } | null;
      } | null;
    } | null;
  } | null;
  courseCount: number;
}>;

// Source: ../sanity/queries/instructors.ts
// Variable: INSTRUCTOR_BY_SLUG_QUERY
// Query: *[_type == "instructor" && slug.current == $slug][0] {      _id,  name,  "slug": slug.current,  expertise,  photo {   _type,  alt,  hotspot,  crop,  asset->{    _id,    url,    metadata { lqip, dimensions { width, height, aspectRatio } }  } },    bio,    "courses": *[_type == "course" && instructor._ref == ^._id && defined(slug.current)]      | order(title asc) {   _id,  title,  "slug": slug.current,  summary,  level,  priceDisplay,  popular,  studentCountDisplay,  coverImage {   _type,  alt,  hotspot,  crop,  asset->{    _id,    url,    metadata { lqip, dimensions { width, height, aspectRatio } }  } },  instructor->{   _id,  name,  "slug": slug.current,  expertise,  photo {   _type,  alt,  hotspot,  crop,  asset->{    _id,    url,    metadata { lqip, dimensions { width, height, aspectRatio } }  } } },  category->{   _id,  title,  "slug": slug.current },  "moduleCount": count(modules),  "lessonCount": count(modules[].lessons[]),  "durationSeconds": math::sum(modules[].lessons[]->durationSeconds) }  }
export type INSTRUCTOR_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: string;
  expertise: Array<string> | null;
  photo: {
    _type: "image";
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
          aspectRatio: number;
        } | null;
      } | null;
    } | null;
  } | null;
  bio: string | null;
  courses: Array<{
    _id: string;
    title: string;
    slug: string;
    summary: string | null;
    level: "advanced" | "beginner" | "intermediate";
    priceDisplay: string | null;
    popular: boolean | null;
    studentCountDisplay: string | null;
    coverImage: {
      _type: "image";
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
            aspectRatio: number;
          } | null;
        } | null;
      } | null;
    } | null;
    instructor: {
      _id: string;
      name: string;
      slug: string;
      expertise: Array<string> | null;
      photo: {
        _type: "image";
        alt: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number;
              height: number;
              aspectRatio: number;
            } | null;
          } | null;
        } | null;
      } | null;
    } | null;
    category: {
      _id: string;
      title: string;
      slug: string;
    } | null;
    moduleCount: number | null;
    lessonCount: number | null;
    durationSeconds: number | null;
  }>;
} | null;

// Source: ../sanity/queries/lessons.ts
// Variable: LESSON_BY_SLUG_QUERY
// Query: *[_type == "lesson" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    videoUrl,    poster {   _type,  alt,  hotspot,  crop,  asset->{    _id,    url,    metadata { lqip, dimensions { width, height, aspectRatio } }  } },    durationSeconds,    freePreview,    studentCountDisplay,    notes,    keyPoints,    proTip,    resources[] { _key, type, title, description, url },    "course": *[_type == "course" && references(^._id)] | order(_createdAt asc)[0] {      _id,      title,      "slug": slug.current,      level,      coverImage {   _type,  alt,  hotspot,  crop,  asset->{    _id,    url,    metadata { lqip, dimensions { width, height, aspectRatio } }  } },      instructor->{   _id,  name,  "slug": slug.current,  expertise,  photo {   _type,  alt,  hotspot,  crop,  asset->{    _id,    url,    metadata { lqip, dimensions { width, height, aspectRatio } }  } } },      modules[] {        _key,        title,        lessons[]->{   _id,  title,  "slug": slug.current,  durationSeconds,  freePreview,  poster {   _type,  alt,  hotspot,  crop,  asset->{    _id,    url,    metadata { lqip, dimensions { width, height, aspectRatio } }  } } }      }    }  }
export type LESSON_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  videoUrl: string | null;
  poster: {
    _type: "image";
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number;
          height: number;
          aspectRatio: number;
        } | null;
      } | null;
    } | null;
  } | null;
  durationSeconds: number | null;
  freePreview: boolean | null;
  studentCountDisplay: string | null;
  notes: BlockContent | null;
  keyPoints: Array<string> | null;
  proTip: string | null;
  resources: Array<{
    _key: string;
    type: "article" | "code" | "documentation" | "download" | "other" | "video";
    title: string;
    description: string | null;
    url: string;
  }> | null;
  course: {
    _id: string;
    title: string;
    slug: string;
    level: "advanced" | "beginner" | "intermediate";
    coverImage: {
      _type: "image";
      alt: string | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: {
            width: number;
            height: number;
            aspectRatio: number;
          } | null;
        } | null;
      } | null;
    } | null;
    instructor: {
      _id: string;
      name: string;
      slug: string;
      expertise: Array<string> | null;
      photo: {
        _type: "image";
        alt: string | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: {
              width: number;
              height: number;
              aspectRatio: number;
            } | null;
          } | null;
        } | null;
      } | null;
    } | null;
    modules: Array<{
      _key: string;
      title: string;
      lessons: Array<{
        _id: string;
        title: string;
        slug: string;
        durationSeconds: number | null;
        freePreview: boolean | null;
        poster: {
          _type: "image";
          alt: string | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            url: string;
            metadata: {
              lqip: string | null;
              dimensions: {
                width: number;
                height: number;
                aspectRatio: number;
              } | null;
            } | null;
          } | null;
        } | null;
      }> | null;
    }> | null;
  } | null;
} | null;

// Source: ../sanity/queries/lessons.ts
// Variable: LESSON_SLUGS_QUERY
// Query: *[_type == "lesson" && defined(slug.current)].slug.current
export type LESSON_SLUGS_QUERY_RESULT = Array<string>;

// Source: ../sanity/queries/progress.ts
// Variable: PROGRESS_FOR_USER_QUERY
// Query: *[_type == "progress" && userId == $userId] | order(updatedAt desc) {    _id,    "lessonId": lesson._ref,    completed,    completedAt,    resumeSeconds,    updatedAt  }
export type PROGRESS_FOR_USER_QUERY_RESULT = Array<{
  _id: string;
  lessonId: string;
  completed: boolean | null;
  completedAt: string | null;
  resumeSeconds: number | null;
  updatedAt: string | null;
}>;

// Source: ../sanity/queries/progress.ts
// Variable: PROGRESS_FOR_LESSON_QUERY
// Query: *[_type == "progress" && userId == $userId && lesson._ref == $lessonId][0] {    _id,    "lessonId": lesson._ref,    completed,    completedAt,    resumeSeconds,    updatedAt  }
export type PROGRESS_FOR_LESSON_QUERY_RESULT = {
  _id: string;
  lessonId: string;
  completed: boolean | null;
  completedAt: string | null;
  resumeSeconds: number | null;
  updatedAt: string | null;
} | null;

// Source: ../sanity/queries/videos.ts
// Variable: VIDEO_BY_VIDEO_ID_QUERY
// Query: *[_type == "video" && videoId == $videoId] | order(_createdAt asc)[0] {    _id,    videoId,    provider,    providerVideoId,    sourceUrl,    title,    durationSeconds,    ingestedAt,    chapters[] { _key, startSeconds, label },    "transcriptChunkCount": count(transcriptChunks)  }
export type VIDEO_BY_VIDEO_ID_QUERY_RESULT = {
  _id: string;
  videoId: string;
  provider: "bunny" | "vimeo" | "youtube";
  providerVideoId: string | null;
  sourceUrl: string;
  title: string | null;
  durationSeconds: number | null;
  ingestedAt: string | null;
  chapters: Array<{
    _key: string;
    startSeconds: number;
    label: string;
  }> | null;
  transcriptChunkCount: number | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[\n    _type == "assessment" &&\n    lesson._ref == $lessonId &&\n    reviewStatus == "approved" &&\n    sourceStatus == "current" &&\n    !(_id in path("drafts.**")) &&\n    !(_id in path("versions.**")) &&\n    count(*[\n      _type == "assessment" &&\n      familyId == ^.familyId &&\n      version > ^.version &&\n      reviewStatus == "approved" &&\n      sourceStatus == "current" &&\n      !(_id in path("drafts.**")) &&\n      !(_id in path("versions.**"))\n    ]) == 0\n  ] | order(familyId asc, version desc)[0...50] {\n    _id,\n    _rev,\n    familyId,\n    version,\n    "lessonId": lesson._ref,\n    type,\n    responseFormat,\n    question,\n    "options": options[] { "id": _key, text }\n  }\n': LESSON_PRACTICE_ITEMS_QUERY_RESULT;
    '\n  *[_type == "category" && defined(slug.current)] | order(title asc) {\n    \n  _id,\n  title,\n  "slug": slug.current\n,\n    description,\n    "courseCount": count(*[_type == "course" && category._ref == ^._id])\n  }\n': CATEGORIES_QUERY_RESULT;
    '\n  *[_type == "category" && slug.current == $slug][0] {\n    \n  _id,\n  title,\n  "slug": slug.current\n,\n    description,\n    "courses": *[_type == "course" && category._ref == ^._id && defined(slug.current)]\n      | order(popular desc, title asc) { \n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  level,\n  priceDisplay,\n  popular,\n  studentCountDisplay,\n  coverImage { \n  _type,\n  alt,\n  hotspot,\n  crop,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height, aspectRatio } }\n  }\n },\n  instructor->{ \n  _id,\n  name,\n  "slug": slug.current,\n  expertise,\n  photo { \n  _type,\n  alt,\n  hotspot,\n  crop,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height, aspectRatio } }\n  }\n }\n },\n  category->{ \n  _id,\n  title,\n  "slug": slug.current\n },\n  "moduleCount": count(modules),\n  "lessonCount": count(modules[].lessons[]),\n  "durationSeconds": math::sum(modules[].lessons[]->durationSeconds)\n }\n  }\n': CATEGORY_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "course" && defined(slug.current)]\n    | order(popular desc, title asc) {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  level,\n  priceDisplay,\n  popular,\n  studentCountDisplay,\n  coverImage { \n  _type,\n  alt,\n  hotspot,\n  crop,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height, aspectRatio } }\n  }\n },\n  instructor->{ \n  _id,\n  name,\n  "slug": slug.current,\n  expertise,\n  photo { \n  _type,\n  alt,\n  hotspot,\n  crop,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height, aspectRatio } }\n  }\n }\n },\n  category->{ \n  _id,\n  title,\n  "slug": slug.current\n },\n  "moduleCount": count(modules),\n  "lessonCount": count(modules[].lessons[]),\n  "durationSeconds": math::sum(modules[].lessons[]->durationSeconds)\n\n  }\n': COURSES_QUERY_RESULT;
    '\n  *[_type == "course" && defined(slug.current)].slug.current\n': COURSE_SLUGS_QUERY_RESULT;
    '\n  *[_type == "course" && slug.current == $slug][0] {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  level,\n  priceDisplay,\n  popular,\n  studentCountDisplay,\n  coverImage { \n  _type,\n  alt,\n  hotspot,\n  crop,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height, aspectRatio } }\n  }\n },\n  instructor->{ \n  _id,\n  name,\n  "slug": slug.current,\n  expertise,\n  photo { \n  _type,\n  alt,\n  hotspot,\n  crop,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height, aspectRatio } }\n  }\n }\n },\n  category->{ \n  _id,\n  title,\n  "slug": slug.current\n },\n  "moduleCount": count(modules),\n  "lessonCount": count(modules[].lessons[]),\n  "durationSeconds": math::sum(modules[].lessons[]->durationSeconds)\n,\n    instructor->{ \n  _id,\n  name,\n  "slug": slug.current,\n  expertise,\n  photo { \n  _type,\n  alt,\n  hotspot,\n  crop,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height, aspectRatio } }\n  }\n }\n, bio },\n    learningOutcomes[] { _key, icon, title, description },\n    modules[] {\n      _key,\n      title,\n      summary,\n      lessons[]->{ \n  _id,\n  title,\n  "slug": slug.current,\n  durationSeconds,\n  freePreview,\n  poster { \n  _type,\n  alt,\n  hotspot,\n  crop,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height, aspectRatio } }\n  }\n }\n }\n    }\n  }\n': COURSE_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "instructor" && defined(slug.current)] | order(name asc) {\n    \n  _id,\n  name,\n  "slug": slug.current,\n  expertise,\n  photo { \n  _type,\n  alt,\n  hotspot,\n  crop,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height, aspectRatio } }\n  }\n }\n,\n    "courseCount": count(*[_type == "course" && instructor._ref == ^._id])\n  }\n': INSTRUCTORS_QUERY_RESULT;
    '\n  *[_type == "instructor" && slug.current == $slug][0] {\n    \n  _id,\n  name,\n  "slug": slug.current,\n  expertise,\n  photo { \n  _type,\n  alt,\n  hotspot,\n  crop,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height, aspectRatio } }\n  }\n }\n,\n    bio,\n    "courses": *[_type == "course" && instructor._ref == ^._id && defined(slug.current)]\n      | order(title asc) { \n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  level,\n  priceDisplay,\n  popular,\n  studentCountDisplay,\n  coverImage { \n  _type,\n  alt,\n  hotspot,\n  crop,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height, aspectRatio } }\n  }\n },\n  instructor->{ \n  _id,\n  name,\n  "slug": slug.current,\n  expertise,\n  photo { \n  _type,\n  alt,\n  hotspot,\n  crop,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height, aspectRatio } }\n  }\n }\n },\n  category->{ \n  _id,\n  title,\n  "slug": slug.current\n },\n  "moduleCount": count(modules),\n  "lessonCount": count(modules[].lessons[]),\n  "durationSeconds": math::sum(modules[].lessons[]->durationSeconds)\n }\n  }\n': INSTRUCTOR_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "lesson" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    videoUrl,\n    poster { \n  _type,\n  alt,\n  hotspot,\n  crop,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height, aspectRatio } }\n  }\n },\n    durationSeconds,\n    freePreview,\n    studentCountDisplay,\n    notes,\n    keyPoints,\n    proTip,\n    resources[] { _key, type, title, description, url },\n    "course": *[_type == "course" && references(^._id)] | order(_createdAt asc)[0] {\n      _id,\n      title,\n      "slug": slug.current,\n      level,\n      coverImage { \n  _type,\n  alt,\n  hotspot,\n  crop,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height, aspectRatio } }\n  }\n },\n      instructor->{ \n  _id,\n  name,\n  "slug": slug.current,\n  expertise,\n  photo { \n  _type,\n  alt,\n  hotspot,\n  crop,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height, aspectRatio } }\n  }\n }\n },\n      modules[] {\n        _key,\n        title,\n        lessons[]->{ \n  _id,\n  title,\n  "slug": slug.current,\n  durationSeconds,\n  freePreview,\n  poster { \n  _type,\n  alt,\n  hotspot,\n  crop,\n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions { width, height, aspectRatio } }\n  }\n }\n }\n      }\n    }\n  }\n': LESSON_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "lesson" && defined(slug.current)].slug.current\n': LESSON_SLUGS_QUERY_RESULT;
    '\n  *[_type == "progress" && userId == $userId] | order(updatedAt desc) {\n    _id,\n    "lessonId": lesson._ref,\n    completed,\n    completedAt,\n    resumeSeconds,\n    updatedAt\n  }\n': PROGRESS_FOR_USER_QUERY_RESULT;
    '\n  *[_type == "progress" && userId == $userId && lesson._ref == $lessonId][0] {\n    _id,\n    "lessonId": lesson._ref,\n    completed,\n    completedAt,\n    resumeSeconds,\n    updatedAt\n  }\n': PROGRESS_FOR_LESSON_QUERY_RESULT;
    '\n  *[_type == "video" && videoId == $videoId] | order(_createdAt asc)[0] {\n    _id,\n    videoId,\n    provider,\n    providerVideoId,\n    sourceUrl,\n    title,\n    durationSeconds,\n    ingestedAt,\n    chapters[] { _key, startSeconds, label },\n    "transcriptChunkCount": count(transcriptChunks)\n  }\n': VIDEO_BY_VIDEO_ID_QUERY_RESULT;
  }
}
